name: Sub Workflow

on:
  workflow_dispatch:
    inputs:
      parameter_file:
        description: 'Path to parameter file'
        required: true

jobs:
  sub_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read Parameter from File
        run: |
          cat ${{ github.event.inputs.parameter_file }}
